# Generated by Django 2.1.2 on 2018-10-07 15:11

from django.db import migrations, models
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0003_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicBuilding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=10000)),
                ('address', models.CharField(max_length=300)),
                ('hoursOperation', models.TextField(max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OutdoorAttraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=10000)),
                ('address', models.CharField(max_length=300)),
                ('type', models.CharField(choices=[('Park', 'Park'), ('Trail', 'Trail'), ('Monument', 'Monument'), ('Garden', 'Garden')], max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=10000)),
                ('address', models.CharField(max_length=300)),
                ('hoursOperation', models.TextField(max_length=500)),
                ('menu', models.CharField(max_length=300)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
