# Generated by Django 2.1.2 on 2018-10-07 20:10

from django.db import migrations, models
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0004_auto_20181007_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='Museum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=10000)),
                ('address', models.CharField(max_length=300)),
                ('hours', models.TextField(max_length=500)),
                ('price', models.CharField(choices=[('$', '$'), ('$$', '$$'), ('$$$', '$$$')], max_length=5)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SportsFacility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=10000)),
                ('address', models.CharField(max_length=300)),
                ('sports', models.CharField(max_length=150)),
                ('teams', models.CharField(max_length=100)),
                ('schedule', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='outdoorattraction',
            name='type',
            field=models.CharField(choices=[('Park', 'Park'), ('Trail', 'Trail'), ('Monument', 'Monument'), ('Garden', 'Garden'), ('Natural Wonder', 'Natural Wonder'), ('Public Art', 'Public Art'), ('Spooky Spot', 'Spooky Spot')], max_length=50),
        ),
    ]
