# Generated by Django 2.1.2 on 2018-10-08 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0005_auto_20181007_2010'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
